module.exports = {
'af' : 'Afghanistan',
'ax' : 'Aland Islands',
'al' : 'Albania',
'dz' : 'Algeria',
'as' : 'American Samoa',
'ad' : 'Andorra',
'ao' : 'Angola',
'ai' : 'Anguilla',
'aq' : 'Antarctica',
'ag' : 'Antigua and Barbuda',
'ar' : 'Argentina',
'am' : 'Armenia',
'aw' : 'Aruba',
'ac' : 'Ascension Island',
'au' : 'Australia',
'at' : 'Austria',
'az' : 'Azerbaijan',
'bs' : 'Bahamas',
'bh' : 'Bahrain',
'bd' : 'Bangladesh',
'bb' : 'Barbados',
'by' : 'Belarus',
'be' : 'Belgium',
'bz' : 'Belize',
'bj' : 'Benin',
'bm' : 'Bermuda',
'bt' : 'Bhutan',
'bo' : 'Bolivia (Plurinational State of)',	
'ba' : 'Bosnia and Herzegovina',
'bw' : 'Botswana',
'bv' : 'Bouvet Island',
'br' : 'Brazil',
'io' : 'British Indian Ocean Territory',
'bn' : 'Brunei Darussalam',
'bg' : 'Bulgaria',
'bf' : 'Burkina Faso',
'bi' : 'Burundi',
'kh' : 'Cambodia',
'cm' : 'Cameroon',
'ca' : 'Canada',
'cv' : 'Cape Verde',
'ky' : 'Cayman Islands',
'cf' : 'Central African Republic',
'td' : 'Chad',
'cl' : 'Chile',
'cn' : 'China',
'cx' : 'Christmas Island',
'cc' : 'Cocos Islands',
'co' : 'Colombia',
'mp' : 'Commonwealth of the Northern Mariana Islands',
'km' : 'Comoros',
'cg' : 'Congo',
'ck' : 'Cook Islands',
'cr' : 'Costa Rica',
'ci' : 'Cote d\'Ivoire',
'hr' : 'Croatia',
'cu' : 'Cuba',
'cy' : 'Cyprus',
'cz' : 'Czech Repubic', 
'kp' : 'Democratic People\'s Republic of Korea',
'cd' : 'Democratic Republic of the Congo',
'dk' : 'Denmark',
'dj' : 'Djibouti',
'dm' : 'Dominica',
'do' : 'Dominican Republic',
'tp' : 'East Timor',
'ec' : 'Ecuador',
'eg' : 'Egypt',
'sv' : 'El Salvador',
'gq' : 'Equatorial Guinea',
'er' : 'Eritrea',
'ee' : 'Estonia',
'et' : 'Ethiopia',
'eu' : 'European Union',
'fk' : 'Falkland Islands',
'fo' : 'Faroe Islands',
'fj' : 'Fiji',
'fi' : 'Finland',
'fr' : 'France',
'gf' : 'French Guiana',
'pf' : 'French Polynesia',
'tf' : 'French Southern Territories',
'ga' : 'Gabon',
'gm' : 'Gambia',
'ge' : 'Georgia',
'de' : 'Germany',
'gh' : 'Ghana',
'gi' : 'Gibraltar',
'gr' : 'Greece',
'gl' : 'Greenland',
'gd' : 'Grenada',
'gp' : 'Guadeloupe',
'gu' : 'Guam',
'gt' : 'Guatemala',
'gg' : 'Guernsey',
'gn' : 'Guinea',
'gw' : 'Guinea Buissau',
'gy' : 'Guyana',
'ht' : 'Haiti',
'hm' : 'Heard and McDonald Islands',
'va' : 'Holy See',
'hn' : 'Honduras',
'hk' : 'Hong Kong, SAR of China',
'hu' : 'Hungary',
'is' : 'Iceland',
'in' : 'India',
'id' : 'Indonesia',
'iq' : 'Iraq',
'ie' : 'Ireland',
'ir' : 'Islamic Republic of Iran',
'im' : 'Isle of Man',
'il' : 'Israel',
'it' : 'Italy',
'jm' : 'Jamaica',
'jp' : 'Japan',
'je' : 'Jersey',
'jo' : 'Jordan',
'kz' : 'Kazakhstan',
'ke' : 'Kenya',
'ki' : 'Kiribati',
'kw' : 'Kuwait',
'kg' : 'Kyrgyzstan',
'la' : 'Lao People\'s Democratic Republic',
'lv' : 'Latvia',
'lb' : 'Lebanon',
'ls' : 'Lesotho',
'lr' : 'Liberia',
'ly' : 'Libyan Arab Jamahiriya',
'li' : 'Liechtenstein',
'lt' : 'Lithuania',
'lu' : 'Luxembourg',
'mo' : 'Macao, SAR of China',
'mg' : 'Madagascar',
'mw' : 'Malawi',
'my' : 'Malaysia',
'mv' : 'Maldives',
'ml' : 'Mali',
'mt' : 'Malta',
'mh' : 'Marshall Islands',
'mq' : 'Martinique',
'mr' : 'Mauritania',
'mu' : 'Mauritius',
'yt' : 'Mayotte',
'mx' : 'Mexico',
'fm' : 'Micronesia (Federated States of)',
'mc' : 'Monaco',
'mn' : 'Mongolia',
'me' : 'Montenegro',
'ms' : 'Montserrat',
'ma' : 'Morocco',
'mz' : 'Mozambique',
'mm' : 'Myanmar',
'na' : 'Namibia',
'nr' : 'Nauru',
'np' : 'Nepal',
'nl' : 'Netherlands',
'an' : 'Netherlands Antilles',
'nc' : 'New Caledonia',
'nz' : 'New Zealand',
'ni' : 'Nicaragua',
'ne' : 'Niger',
'ng' : 'Nigeria',
'nu' : 'Niue',
'nf' : 'Norfolk Island',
'no' : 'Norway',
'om' : 'Oman',
'pk' : 'Pakistan',
'pw' : 'Palau',
'ps' : 'Palestine',
'pa' : 'Panama',
'pg' : 'Papua New Guinea',
'py' : 'Paraguay',
'pe' : 'Peru',
'ph' : 'Philippines',
'pn' : 'Pitcairn Islands',
'pl' : 'Poland',
'pt' : 'Portugal',
'pr' : 'Puerto Rico',
'qa' : 'Qatar',
'kr' : 'Republic of Korea',
'md' : 'Republic of Moldova',
're' : 'Reunion Island',
'ro' : 'Romania',
'ru' : 'Russian Federation',
'rw' : 'Rwanda',
'bl' : 'Saint Barthelemy',
'kn' : 'Saint Kitts and Nevis',
'lc' : 'Saint Lucia',
'mf' : 'Saint Martin (French part)',
'vc' : 'Saint Vincent and the Grenadines',
'ws' : 'Samoa',
'sm' : 'San Marino',
'st' : 'Sao Tome and Principe',
'sa' : 'Saudi Arabia',
'sn' : 'Senegal',
'rs' : 'Serbia',
'sc' : 'Seychelles',
'sl' : 'Sierra Leone',
'sg' : 'Singapore',
'sk' : 'Slovakia',
'si' : 'Slovenia',
'sb' : 'Solomon Islands',
'so' : 'Somalia',
'za' : 'South Africa',
'gs' : 'South Georgia and the South Sandwich Islands',
'su' : 'Soviet Union',
'es' : 'Spain',
'lk' : 'Sri Lanka',
'sh' : 'St. Helena',
'pm' : 'St. Pierre and Miquelon',
'sd' : 'Sudan',
'sr' : 'Suriname',
'sj' : 'Svalbard and Jan Mayen Islands',
'sz' : 'Swaziland',
'se' : 'Sweden',
'ch' : 'Switzerland',
'sy' : 'Syrian Arab republic',
'tw' : 'Taiwan, Republic of China',
'tj' : 'Tajikistan',
'th' : 'Thailand',
'mk' : 'The Former Yugoslav Republic of Macedonia',
'tl' : 'Timor-Leste',
'tg' : 'Togo',
'tk' : 'Tokelau',
'to' : 'Tonga',
'tt' : 'Trinidad and Tobago',
'tn' : 'Tunisia',
'tr' : 'Turkey',
'tm' : 'Turkmenistan',
'tc' : 'Turks and Caicos Islands',
'tv' : 'Tuvalu',
'ug' : 'Uganda',
'ua' : 'Ukraine',
'ae' : 'United Arab Emirates',
'gb' : 'United Kingdom',
'uk' : 'United Kingdom',
'tz' : 'United Republic of Tanzania',
'us' : 'United States of America',
'uy' : 'Uruguay',
'um' : 'US Minor Outlying Islands',
'uz' : 'Uzbekistan',
'vu' : 'Vanuatu',
've' : 'Venezuela (Bolivarian Republic of)',
'vn' : 'Viet Nam',
'vg' : 'Virgin Islands (British)',
'vi' : 'Virgin Islands (USA)',
'wf' : 'Wallis and Futuna Islands',
'eh' : 'Western Sahara',
'ye' : 'Yemen',
'yu' : 'Yugoslavia',
'zm' : 'Zambia',
'zw' : 'Zimbabwe'
};

//console.log(c);
